create database if not exists DOANTINHOC CHARACTER SET 'utf8' COLLATE 'utf8_general_ci';

use DOANTINHOC;

CREATE TABLE IF NOT EXISTS QUANTRI (
    MAQUANTRI INT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    TENDANGNHAP VARCHAR(50) NOT NULL UNIQUE,
    MATKHAU VARCHAR(50) NOT NULL,
    HOTEN VARCHAR(100) NOT NULL DEFAULT 'no name',
    PRIMARY KEY (MAQUANTRI)
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS NGUOIDUNG (
    MANGUOIDUNG INT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    HOTEN VARCHAR(100) NOT NULL DEFAULT 'no name',
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    TENDANGNHAP VARCHAR(50) NOT NULL UNIQUE,
    MATKHAU VARCHAR(50) NOT NULL,
    DIEM NUMERIC NOT NULL DEFAULT '0',
    /*HE THONG TINH DIEM NGUOI DUNG*/
    TRINHDO VARCHAR(20) NOT NULL,
    /*DUA VAO DIEM DE PHAN CAP TRINH DO*/
    DIACHI VARCHAR(100) NOT NULL,
    SDT NUMERIC UNIQUE,
    THOIDIEMDANGKI DATETIME NOT NULL,
    PRIMARY KEY (MANGUOIDUNG)
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS DANHMUC (
    MADANHMUC INT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    TENDANHMUC VARCHAR(100) NOT NULL UNIQUE,
    MADANHMUCCHA INT(20) NOT NULL DEFAULT '0',
    /*DANH MUC CHUA DANH MUC KHAC*/
    PRIMARY KEY (MADANHMUC)
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS SANPHAM (
    MASANPHAM INT(20) NOT NULL AUTO_INCREMENT,
    MABAIVIET INT(20) NOT NULL,
    HASHTAG VARCHAR(50) NOT NULL,
    TENSANPHAM VARCHAR(50) NOT NULL,
    HANGSANXUAT VARCHAR(50) NOT NULL,
    NGAYSANXUAT DATETIME,
    THONGSOKYTHUAT TEXT,
    HINHANH VARCHAR(100) NOT NULL,
    LIENKET TEXT,
    FULLTEXT KEY (THONGSOKYTHUAT),
    PRIMARY KEY (MASANPHAM)
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS BAIVIET (
    MABAIVIET INT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    MANGUOIDUNG INT(20) unsigned NOT NULL,
    MASANPHAM INT(20) NOT NULL,
    MADANHMUC INT(20) unsigned NULL,
    NOIDUNG LONGTEXT,
    HINHANH VARCHAR(100) NOT NULL,
    NGAYDANGBAI DATETIME NOT NULL,
    KIEMTRA VARCHAR(1) NOT NULL,
    /* QUAN TRI DUYET XEM CO DUOC DANG BAI HAY KHONG*/
    FOREIGN KEY (MASANPHAM)
        REFERENCES SANPHAM(MASANPHAM),
    FOREIGN KEY (MANGUOIDUNG)
        REFERENCES NGUOIDUNG(MANGUOIDUNG),
    FOREIGN KEY (MADANHMUC)
        REFERENCES DANHMUC (MADANHMUC),
    PRIMARY KEY (MABAIVIET)
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS BINHLUAN (
    MABINHLUAN INT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    TENDANGNHAP VARCHAR(50) NOT NULL UNIQUE,
    NOIDUNG TEXT NOT NULL,
    THOIGIAN DATETIME NOT NULL,
    KIEMTRA VARCHAR(1) NOT NULL,
    /*QUAN TRI DUYET BINH LUAN CO DUOC HIEN THI HAY KHONG*/
    MABAIVIET INT(20) unsigned  NULL,
    FOREIGN KEY (MABAIVIET)
        REFERENCES BAIVIET (MABAIVIET),
    PRIMARY KEY (MABINHLUAN)
)  ENGINE=INNODB;